name: Package and Release NAntUtilities

on:
  push:
    branches:
      - release

jobs:
  Release:
    runs-on: windows-latest

    steps:
      - name: Setup Nuget Source
        id: setup_nuget_source
        shell: powershell
        env:
          GH_USERNAME: ${{ secrets.EKEEL_GITHUB_USERNAME }}
          GH_TOKEN: ${{ secrets.EKEEL_GITHUB_TOKEN }}
        run: dotnet nuget add source --username "$env:GH_USERNAME" -p "$env:GH_TOKEN" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ekeel/index.json"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Package
        id: package
        shell: powershell
        run: |
          cd NAntUtilities
          dotnet pack -c Release

      - name: Push Package
        id: push_package
        shell: powershell
        run: dotnet nuget push "NAntUtilities/bin/Release/*.nupkg" --source github --skip-duplicate
