name: Validate NAntUtilities

on:
  push:
    branches:
      - main

jobs:
  Validate:
    runs-on: windows-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Package
        id: package
        run: |
          cd NAntUtilities
          dotnet pack -c Release

      - name: Get Name
        id: get_name
        shell: powershell
        run: |
          $name = (Get-ChildItem .\NAntUtilities\bin\Release\*.nupkg)[0].Name
          echo "::set-output name=name::$name"