name: Validate NAntSqlHandler

on:
  push:
    branches:
      - main

jobs:
  Validate:
    runs-on: windows-latest

    steps:
      - name: Setup Nuget Source
        id: setup_nuget_source
        shell: powershell
        run: dotnet nuget add source --username "ekeel" -p "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ekeel/index.json"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Package
        id: package
        run: |
          cd NAntSqlHandler
          dotnet pack -c Release
