name: Pack/Release NAntExtensions

on:
  push:
    branches:
      - release

jobs:
  prnantutilities:
    name: Pack/Release NAntUtilities
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[no ci]') && !contains(github.event.head_commit.message, '[no utilities]')"

    steps:
      - name: Setup Nuget Source
        id: setup_nuget_source
        shell: powershell
        run: dotnet nuget add source --username "ekeel" -p "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ekeel/index.json"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Package
        id: package
        shell: powershell
        run: |
          cd NAntUtilities
          dotnet pack -c Release

      - name: Push Package
        id: push_package
        shell: powershell
        run: |
          cd NAntUtilities
          dotnet nuget push ".\bin\Release\*.nupkg" --source github --skip-duplicate
  
  prnantsqltasks:
    name: Pack/Release NAntSqlTasks
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[no ci]') && !contains(github.event.head_commit.message, '[no sqltasks]')"

    steps:
      - name: Setup Nuget Source
        id: setup_nuget_source
        shell: powershell
        run: dotnet nuget add source --username "ekeel" -p "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ekeel/index.json"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Package
        id: package
        run: |
          cd NAntSqlTasks
          dotnet pack -c Release

      - name: Push Package
        id: push_package
        shell: powershell
        run: |
          cd NAntSqlTasks
          dotnet nuget push ".\bin\Release\*.nupkg" --source github --skip-duplicate
          