name: Pack/Release NAntExtensions

on:
  push:
    branches:
      - release

  workflow_dispatch:
    inputs:
      tasks:
        description: 'A placeholder'
        required: true

jobs:
  prnantutilities:
    name: Pack/Release NAntUtilities
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[no ci]') && !contains(github.event.head_commit.message, '[no utilities]')"

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Package
        id: package
        shell: powershell
        run: |
          cd NAntUtilities
          dotnet pack -c Release

      - name: Install jfrog
        id: install_jfrog
        uses: jfrog/setup-jfrog-cli@v2

      - name: Push Package
        id: push_package
        shell: powershell
        run: |
          cd .\NAntUtilities\bin\Release
          $nugetPackage = Get-Item "*.nupkg" | select -First 1
          jfrog rt u $($nugetPackage.Name) ekeel-nuget --url='https://ekeel.jfrog.io/artifactory' --user "${{ secrets.JFROG_USERNAME }}" --password "${{ secrets.JFROG_PASSWORD }}"
  
  prnantsqltasks:
    name: Pack/Release NAntSqlTasks
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[no ci]') && !contains(github.event.head_commit.message, '[no sqltasks]')"

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Configure Nuget
        id: configure_nuget
        shell: powershell
        run: dotnet nuget add source --username ${{ secrets.JFROG_USERNAME }} -p ${{ secrets.JFROG_PASSWORD }} --name ekeel.jfrog.io "https://ekeel.jfrog.io/artifactory/api/nuget/v3/ekeel-nuget"

      - name: Package
        id: package
        run: |
          cd NAntSqlTasks
          dotnet pack -c Release

      - name: Install jfrog
        id: install_jfrog
        uses: jfrog/setup-jfrog-cli@v2

      - name: Push Package
        id: push_package
        shell: powershell
        run: |
          cd .\NAntSqlTasks\bin\Release
          $nugetPackage = Get-Item "*.nupkg" | select -First 1
          jfrog rt u $($nugetPackage.Name) ekeel-nuget --url='https://ekeel.jfrog.io/artifactory' --user ${{ secrets.JFROG_USERNAME }} --password ${{ secrets.JFROG_PASSWORD }}
